package org.whz.securityjwt.model;

public class UmsRolePermissionRelation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_role_permission_relation.id
     *
     * @mbg.generated Tue Oct 13 10:58:56 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_role_permission_relation.role_id
     *
     * @mbg.generated Tue Oct 13 10:58:56 CST 2020
     */
    private Long roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_role_permission_relation.permission_id
     *
     * @mbg.generated Tue Oct 13 10:58:56 CST 2020
     */
    private Long permissionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_role_permission_relation.id
     *
     * @return the value of ums_role_permission_relation.id
     *
     * @mbg.generated Tue Oct 13 10:58:56 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_role_permission_relation.id
     *
     * @param id the value for ums_role_permission_relation.id
     *
     * @mbg.generated Tue Oct 13 10:58:56 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_role_permission_relation.role_id
     *
     * @return the value of ums_role_permission_relation.role_id
     *
     * @mbg.generated Tue Oct 13 10:58:56 CST 2020
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_role_permission_relation.role_id
     *
     * @param roleId the value for ums_role_permission_relation.role_id
     *
     * @mbg.generated Tue Oct 13 10:58:56 CST 2020
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_role_permission_relation.permission_id
     *
     * @return the value of ums_role_permission_relation.permission_id
     *
     * @mbg.generated Tue Oct 13 10:58:56 CST 2020
     */
    public Long getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_role_permission_relation.permission_id
     *
     * @param permissionId the value for ums_role_permission_relation.permission_id
     *
     * @mbg.generated Tue Oct 13 10:58:56 CST 2020
     */
    public void setPermissionId(Long permissionId) {
        this.permissionId = permissionId;
    }
}