package org.whz.securityjwt.mapper;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.whz.securityjwt.model.UmsAdmin;

@Mapper
public interface UmsAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin
     *
     * @mbg.generated Mon Oct 12 09:23:03 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin
     *
     * @mbg.generated Mon Oct 12 09:23:03 CST 2020
     */
    int insert(UmsAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin
     *
     * @mbg.generated Mon Oct 12 09:23:03 CST 2020
     */
    int insertSelective(UmsAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin
     *
     * @mbg.generated Mon Oct 12 09:23:03 CST 2020
     */
    UmsAdmin selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin
     *
     * @mbg.generated Mon Oct 12 09:23:03 CST 2020
     */
    int updateByPrimaryKeySelective(UmsAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin
     *
     * @mbg.generated Mon Oct 12 09:23:03 CST 2020
     */
    int updateByPrimaryKey(UmsAdmin record);

    /**
     * 根据用户名查询管理员账户
     * @param username
     * @return
     */
    UmsAdmin selectUmsAdminByUsername(@Param("username") String username);

    /**
     * 查询数据库中是否存中指定用户名
     * @param username
     * @return
     */
    int countUsername(@Param("username") String username);
}