package org.whz.securityjwt.mapper;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.whz.securityjwt.model.UmsPermission;

import java.util.List;
import java.util.Set;

@Mapper
public interface UmsPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_permission
     *
     * @mbg.generated Mon Oct 12 09:22:41 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_permission
     *
     * @mbg.generated Mon Oct 12 09:22:41 CST 2020
     */
    int insert(UmsPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_permission
     *
     * @mbg.generated Mon Oct 12 09:22:41 CST 2020
     */
    int insertSelective(UmsPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_permission
     *
     * @mbg.generated Mon Oct 12 09:22:41 CST 2020
     */
    UmsPermission selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_permission
     *
     * @mbg.generated Mon Oct 12 09:22:41 CST 2020
     */
    int updateByPrimaryKeySelective(UmsPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_permission
     *
     * @mbg.generated Mon Oct 12 09:22:41 CST 2020
     */
    int updateByPrimaryKey(UmsPermission record);

    /**
     * 通过角色查询权限(userID -> 角色 -> 权限)
     * @param userId
     * @return
     */
    Set<UmsPermission> selectPermissionByRole(@Param("userId") Long userId);

    /**
     * 加权限
     * @param userId
     * @return
     */
    Set<UmsPermission> selectPermissionByUserAdd(@Param("userId") Long userId);

    /**
     * 减权限
     * @param userId
     * @return
     */
    Set<UmsPermission> selectPermissionByUserRed(@Param("userId") Long userId);
}